// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: bufbuild/example/opt/v1/opt.proto

package v1

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_bufbuild_example_opt_v1_opt_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         65114,
		Name:          "bufbuild.example.opt.v1.id",
		Tag:           "varint,65114,opt,name=id",
		Filename:      "bufbuild/example/opt/v1/opt.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// optional bool id = 65114;
	E_Id = &file_bufbuild_example_opt_v1_opt_proto_extTypes[0]
)

var File_bufbuild_example_opt_v1_opt_proto protoreflect.FileDescriptor

var file_bufbuild_example_opt_v1_opt_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x75, 0x66, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x6f, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x17, 0x62, 0x75, 0x66, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3a, 0x2f,
	0x0a, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xda, 0xfc, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x69, 0x64, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x74,
	0x79, 0x72, 0x72, 0x65, 0x6c, 0x6c, 0x2f, 0x62, 0x75, 0x66, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x70, 0x74, 0x2f, 0x76, 0x31,
}

var file_bufbuild_example_opt_v1_opt_proto_goTypes = []interface{}{
	(*descriptor.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_bufbuild_example_opt_v1_opt_proto_depIdxs = []int32{
	0, // 0: bufbuild.example.opt.v1.id:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bufbuild_example_opt_v1_opt_proto_init() }
func file_bufbuild_example_opt_v1_opt_proto_init() {
	if File_bufbuild_example_opt_v1_opt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bufbuild_example_opt_v1_opt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_bufbuild_example_opt_v1_opt_proto_goTypes,
		DependencyIndexes: file_bufbuild_example_opt_v1_opt_proto_depIdxs,
		ExtensionInfos:    file_bufbuild_example_opt_v1_opt_proto_extTypes,
	}.Build()
	File_bufbuild_example_opt_v1_opt_proto = out.File
	file_bufbuild_example_opt_v1_opt_proto_rawDesc = nil
	file_bufbuild_example_opt_v1_opt_proto_goTypes = nil
	file_bufbuild_example_opt_v1_opt_proto_depIdxs = nil
}
